import type { Metadata } from "next";
import "./globals.css";
import { Overlock, DM_Serif_Display, Roboto, Lora, Montserrat } from "next/font/google";
import { Providers } from "./providers";

const overlock = Overlock({ weight: ["400"], subsets: ["latin"], variable: "--font-overlock", display: "swap" });
const dmSerif = DM_Serif_Display({ weight: ["400"], subsets: ["latin"], variable: "--font-dm-serif", display: "swap" });
const roboto = Roboto({ weight: ["400"], subsets: ["latin"], variable: "--font-roboto", display: "swap" });
const lora = Lora({ weight: ["400"], style: ["italic"], subsets: ["latin"], variable: "--font-lora", display: "swap" });
const montserrat = Montserrat({ weight: ["400"], subsets: ["latin"], variable: "--font-montserrat", display: "swap" });

export const metadata: Metadata = {
  title: "Insspira",
  description: "Generated by Team dev insspira",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" className="notranslate" translate="no">
      <head>
        <meta name="google" content="notranslate" />
      </head>
      <body className={`${overlock.variable} ${dmSerif.variable} ${roboto.variable} ${lora.variable} ${montserrat.variable} antialiased`}>
        {/* Providers client-side */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}