// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Overlock, DM_Serif_Display, Roboto, Lora, Montserrat } from "next/font/google"; 
// import Footer from "@/components/Footer";

const overlock = Overlock({ weight: "400", subsets: ["latin"], variable: "--font-overlock" });
const dmSerif = DM_Serif_Display({ weight: "400", subsets: ["latin"], variable: "--font-dm-serif" });
const roboto = Roboto({ weight: "400", subsets: ["latin"], variable: "--font-roboto" });
const lora = Lora({ weight: "400", subsets: ["latin"], variable: "--font-lora", style: "italic" });
const montserrat = Montserrat({ weight: "400", subsets: ["latin"], variable: "--font-montserrat" });

export const metadata: Metadata = {
  title: "Insspira",
  description: "Generated by Team dev insspira",
  icons: { icon: "/icon.png" },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" className="notranslate" translate="no">
      <head>
        <meta name="google" content="notranslate" />
      </head>
      <body className={`${overlock.variable} ${dmSerif.variable} ${roboto.variable} ${lora.variable} ${montserrat.variable} antialiased`}>
          {children}
          
      </body>
    </html>
  );
}