// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Overlock, DM_Serif_Display, Roboto, Lora, Montserrat } from "next/font/google";
import NavBar from "@/components/navbar/NavBar";
import Footer from "@/components/footer/Footer";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import ChatBot from "@/components/chatBot/ChatBot";

// Usa arrays y agrega display: 'swap'. Evita strings vacíos.
const overlock = Overlock({ weight: ["400"], subsets: ["latin"], variable: "--font-overlock", display: "swap" });
const dmSerif = DM_Serif_Display({ weight: ["400"], subsets: ["latin"], variable: "--font-dm-serif", display: "swap" });
const roboto = Roboto({ weight: ["400"], subsets: ["latin"], variable: "--font-roboto", display: "swap" });
// Lora italic explícito como array
const lora = Lora({ weight: ["400"], style: ["italic"], subsets: ["latin"], variable: "--font-lora", display: "swap" });
const montserrat = Montserrat({ weight: ["400"], subsets: ["latin"], variable: "--font-montserrat", display: "swap" });

// ⚠ Asegúrate que public/icon.png exista. Si no existe, comenta la línea icons.
export const metadata: Metadata = {
  title: "Insspira",
  description: "Generated by Team dev insspira",
  // Si NO tienes /public/icon.png, comenta la línea siguiente:
  // icons: { icon: "/icon.png" },
  // Elimina o NO pongas nada tipo openGraph.images: [""] ni twitter.images: [""].
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" className="notranslate" translate="no">
      <head>
        <meta name="google" content="notranslate" />
      </head>
      <body className={`${overlock.variable} ${dmSerif.variable} ${roboto.variable} ${lora.variable} ${montserrat.variable} antialiased`}>
        <ToastContainer position="top-right" theme="dark" />
        <NavBar />
        {children}
        <ChatBot />
        <Footer />
      </body>
    </html>
  );
}
